### ISSUE TITLE
package list API should use syft packages rpm, dpkg, apk, busybox binaries.

### ISSUE THREAD

**Issue by luhring** [anchore/anchore-engine#682]
Create new handlers within the syft anchore-engine module to replace the existing 10_package_list module.

__Test needed__

1. [x] add functional analyzer tests for debian packages (PR https://github.com/anchore/anchore-engine/pull/694 )
1. [x] add functional analyzer tests for rpm packages 
1. [x] add functional analyzer tests for apline packages (PR https://github.com/anchore/anchore-engine/pull/695)
1. [x] add functional analyzer tests for busybox binaries

**Developer Notes**

- [x] Replace debian analyzer module (PR https://github.com/anchore/anchore-engine/pull/710)
- [x] Replace centos analyzer module (PR https://github.com/anchore/anchore-engine/issues/701)
- [x] Replace alpine analyzer module (https://github.com/anchore/anchore-engine/pull/697)
- [x] Replace busybox analyzer module
