### ISSUE TITLE
Restore content hints functionality for removed analyzer modules

### ISSUE THREAD

**Issue by luhring** [anchore/anchore-engine#703]
The strategy for integrating Syft into anchore-engine has been to:

1. ensure the Syft adequately identifies packages within a container image
1. replace call to a given analyzer module (e.g. `12_gem_package_list.py`) to an analogous data retrieval and transformation operation using Syft output
1. **remove the analyzer module**

For the last step, it's important to note that the individual analyzer modules have been accounting for the updates to the result data based on the "hints file" feature (e.g. https://github.com/anchore/anchore-engine/blob/master/anchore_engine/analyzers/modules/12_gem_package_list.py#L59-L71).

Thus, it's necessary to handle the "hints" data merge in a new way that reconciles the new, Syft-oriented data flow with the expected functionality of the "hints" feature.

**Acceptance criteria:**
1. The "content hints" functionality behaves as expected for all content types, including those whose implementations have been replaced by Syft. (See [Content Hints documentation](https://docs.anchore.com/current/docs/engine/general/concepts/images/analysis/content_hints/))

**Steps to test:**
1. Use (or set up) an instance of Anchore Engine where content hints are enabled.
1. Add an image that includes a hints file that specifies both additional and modifies packages that Syft is cataloging for Engine (e.g. ruby gems).
1. After the analysis is completed, get the image's content and ensure that the data has been updated as expected using the hints file.

**Developer tasks:***
Port the following analyzers to use Syft python package.
- [x] ruby gems analyzer
- [x] java archive analyzer
- [x] javascript npm analyzer
- [x] python analyzer
- [x] rpm analyzer
- [x] debian analyzer

All changes above are being addressed in (https://github.com/anchore/anchore-engine/pull/715)

**Developer notes:**
- Check out how the content hints merging is implemented for various analyzers today (e.g. on `master`, such as https://github.com/anchore/anchore-engine/blob/master/anchore_engine/analyzers/modules/12_gem_package_list.py#L59-L71) for an idea of the expected functionality.
