### ISSUE TITLE
Policy engine should leverage the grype sqlite DB

### ISSUE THREAD

**Issue by wagoodman** [anchore/anchore-engine#706]
This can be broken up into individual user stories that tackle (at least) the following work items:

- [ ] Policy Engine: Replace the feeds client implementation with a call to grype to download a new DB upon a “feeds sync” operation and place it into the catalog.

- [ ] Policy Engine: Expand “feed sync” operation to put the latest sqlite DB archive into the catalog and additionally note the latest available version. Policy engine instances should be checking for the latest version against the catalog and be responsible for an atomic swap between the old and new versions of the grype sqlite DB. 

- [ ] Policy Engine: Replace  “/feeds/”  GET request and “/query/vulnerabilities” GET request handlers to query the grype sqlite DB directly.

- [ ] Policy Engine: Feature removal: ability to toggle feed and feed groups enable/disable state (remove the “/feeds/{feed}” and “/feeds/{feed}/{group}” endpoints)

- [ ] Policy Engine: Modify the “/health” endpoint to indicate readiness only when there is a grype DB that is consistent with the latest available DB (per checking the grype listing file / grype db command

- [ ] Catalog: Update to account for storing binary payloads to support the grype sqlite DB tar.gz archive

**Comment by zhill** [comment]
These are all complete via several PRs and commits, but were tracked in other issues as well. Closing this issue.
