### ISSUE TITLE
Replace the vulnerability matching process with grype call

### ISSUE THREAD

**Issue by wagoodman** [anchore/anchore-engine#707]
This can be broken up into individual user stories that tackle (at least) the following work items:

- [ ] Policy Engine: Remove persisted state: (see google doc)

- [ ] Policy Engine: Add mapper code to take SBOM catalog info and transform for useful input for grype

- [ ] Policy Engine: Replace the “vulnerabilities.py” “vulnerabilities_for_image()” implementation to exec out to grype, returning vulnerability results for the given image SBOM input.

- [ ] Policy Engine: Persist image vulnerability results to the catalog

**Comment by zhill** [comment]
Implemented slightly differently and tracked in other issues. Closing this issue.
